services:
  - postgresql
sudo: required
before-script: 
  - bundle
  - psql -c 'create database ezmeals_test;' -U postgres
language: ruby
rvm:
  - 2.3.1
script: 
  - export RAILS_ENV=test
  - be rake db:create db:migrate
  - be rspec --fail-fast