services:
  - postgresql
sudo: required
TRAVIS_SECURE_ENV_VARS: true
before-script: 
  - bundle
  - psql -c 'create database ezmeals_test;' -U postgres
language: ruby
rvm:
  - 2.3.1
script: 
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rspec --fail-fast
os: osx
secure: "aMBQtoZD5bXXy1yqNXv+d7ujO6ARWCix+snWmyMyAq6Phlr4d7jlLzRl7lRmjSbzgWsENx6lNa4T4tyDZlByAdACW3L9pspwVIAqVdGns3sk/JQ9Ul2/ehlAcNcH4c21adl17/5jWigswKIX2K8mWDhRVZfPju3LK+f3V9uuD96QpspvTlfRm4PmwL5op/FJ44xzECVtELkti+P0IXVLsw6SExzhfQ2YDfnElKyyE0OGrO7KrwDTdvxV2no430ey/0GgWdCl8v0typHYzi9Uada46iIqDYKg25FSkvQ50giJ4uoXcl/yLBmEieppvwriwzKfoinugC/BtJIQ1SEiiDwqtWvAUkqLveVVAY6a5zYSwDPdBb44QxdPGOy7UNnqtm40E8Pr2EqTjzT+p1PUqFTEEyxNC1eC4TZSBd0fwJ8jB8f6Qmq4rDiA4TjD+2gtc0El5t2XHNaITmQXpQD9yozOgVeNeHMsBHkvNeWRUM3r0dg45jEzaT2DDY2N53g3gwc59EWhttvjRz4EkZa+hXNmaJ0KGEef9X8hcN5mLNP0S2fnTNnMaFGiJCS8Gb46e6WxXpw/J2wce3Mb+A1hmTLf4lY5zfIijvcj1BC3MXV7mXtIsOOJKhPzrC2Kl/Pnxod7Pxk83mfVq36KOB7t6RznqJC6IfHz++J47I7+HDg="